import icon from "../../assert/img/icon.svg";
import splash from "../../assert/img/splash.svg";
import avatar from "../../assert/img/user.jpg";
import shop from "../../assert/img/shop.png";
import img_1 from "../../assert/img/1.jpg";
import img_2 from "../../assert/img/2.jpg";
import img_3 from "../../assert/img/3.jpg";
import img_4 from "../../assert/img/4.jpg";
import img_5 from "../../assert/img/5.jpg";
import food from "../../assert/img/food.jpg";
import dish from "../../assert/img/dish.jpg";
import loader from "../../assert/img/bouncing-circles.svg";
export default {avatar,shop,icon,loader,splash,img_1,img_2,img_3,img_4,img_5,food,dish};