let products = [
  {
    name: "Acrylic Paint Set",
    description: "A set of vibrant acrylic paints for all your creative needs.",
    image: "https://www.example.com/product-image1.jpg",
    brand: { name: "Artistry" },
    offers: {
      "@type": "Offer",
      price: 29.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "ART-PAINT-001",
    },
    department: "Arts & Crafts",
    category: "Drawing & Painting Supplies",
    subcategory: "Paints & Brushes",
    segment: "Acrylic Paints",
    color: "Multi",
    size: "Set of 12",
    material: "Acrylic",
    mpn: "AP-123456",
    url: "https://www.example.com/product-page1",
    rating: { rate: 4.5, count: 150 },
    review: [
      {
        author: "Jane Smith",
        reviewBody: "These paints are fantastic!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Sketching Pencils Set",
    description: "A complete set of sketching pencils for artists.",
    image: "https://www.example.com/product-image2.jpg",
    brand: { name: "SketchPro" },
    offers: {
      "@type": "Offer",
      price: 19.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "SKETCH-001",
    },
    department: "Arts & Crafts",
    category: "Drawing & Painting Supplies",
    subcategory: "Pencils & Charcoal",
    segment: "Sketching Pencils",
    color: "Graphite",
    size: "Set of 10",
    material: "Wood",
    mpn: "SP-123456",
    url: "https://www.example.com/product-page2",
    rating: { rate: 4.2, count: 200 },
    review: [
      {
        author: "Mark Johnson",
        reviewBody: "Great quality pencils for sketching.",
        reviewRating: {
          ratingValue: 4,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Watercolor Paper Pad",
    description: "High-quality watercolor paper for artists.",
    image: "https://www.example.com/product-image3.jpg",
    brand: { name: "Artisan" },
    offers: {
      "@type": "Offer",
      price: 15.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "WATER-PAPER-001",
    },
    department: "Arts & Crafts",
    category: "Drawing & Painting Supplies",
    subcategory: "Drawing Paper & Canvas",
    segment: "Watercolor Paper",
    color: "White",
    size: "9x12 inches",
    material: "Paper",
    mpn: "WP-123456",
    url: "https://www.example.com/product-page3",
    rating: { rate: 4.7, count: 120 },
    review: [
      {
        author: "Emily Davis",
        reviewBody: "Perfect for watercolor painting!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Clay Modeling Kit",
    description: "A complete kit for clay modeling enthusiasts.",
    image: "https://www.example.com/product-image4.jpg",
    brand: { name: "CraftyHands" },
    offers: {
      "@type": "Offer",
      price: 24.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "CLAY-KIT-001",
    },
    department: "Arts & Crafts",
    category: "Sculpting & Molding",
    subcategory: "Clay & Sculpting Materials",
    segment: "Modeling Clay",
    color: "Multi",
    size: "Set of 8",
    material: "Clay",
    mpn: "CK-123456",
    url: "https://www.example.com/product-page4",
    rating: { rate: 4.6, count: 90 },
    review: [
      {
        author: "Sarah Lee",
        reviewBody: "This kit has everything I need for my projects!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Jewelry Making Starter Kit",
    description: "A comprehensive kit for beginners in jewelry making.",
    image: "https://www.example.com/product-image5.jpg",
    brand: { name: "BeadCraft" },
    offers: {
      "@type": "Offer",
      price: 39.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "JEWELRY-KIT-001",
    },
    department: "Arts & Crafts",
    category: "Jewelry Making",
    subcategory: "Jewelry Making Tools & Equipment",
    segment: "Starter Kit",
    color: "Multi",
    size: "One Size",
    material: "Various",
    mpn: "JK-123456",
    url: "https://www.example.com/product-page5",
    rating: { rate: 4.8, count: 75 },
    review: [
      {
        author: "Anna Brown",
        reviewBody: "Perfect for getting started with jewelry making!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Cardstock Paper Pack",
    description: "A pack of high-quality cardstock paper for various crafts.",
    image: "https://www.example.com/product-image6.jpg",
    brand: { name: "CraftyPaper" },
    offers: {
      "@type": "Offer",
      price: 14.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "CARDSTOCK-001",
    },
    department: "Arts & Crafts",
    category: "Paper Crafts",
    subcategory: "Cardstock & Paper",
    segment: "Cardstock",
    color: "Assorted",
    size: "8.5x11 inches",
    material: "Paper",
    mpn: "CP-123456",
    url: "https://www.example.com/product-page6",
    rating: { rate: 4.4, count: 110 },
    review: [
      {
        author: "Tom White",
        reviewBody: "Great quality cardstock for my projects.",
        reviewRating: {
          ratingValue: 4,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Sculpting Tools Set",
    description: "A set of essential tools for sculpting and molding.",
    image: "https://www.example.com/product-image7.jpg",
    brand: { name: "SculptMaster" },
    offers: {
      "@type": "Offer",
      price: 22.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "SCULPT-TOOLS-001",
    },
    department: "Arts & Crafts",
    category: "Sculpting & Molding",
    subcategory: "Sculpting Tools & Equipment",
    segment: "Sculpting Tools",
    color: "Silver",
    size: "Set of 5",
    material: "Metal",
    mpn: "ST-123456",
    url: "https://www.example.com/product-page7",
    rating: { rate: 4.3, count: 85 },
    review: [
      {
        author: "Lisa Green",
        reviewBody: "These tools are perfect for detailed work.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Beading Wire",
    description: "Durable beading wire for jewelry making.",
    image: "https://www.example.com/product-image8.jpg",
    brand: { name: "BeadMaster" },
    offers: {
      "@type": "Offer",
      price: 9.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "BEADING-WIRE-001",
    },
    department: "Arts & Crafts",
    category: "Jewelry Making",
    subcategory: "Jewelry Wire & String",
    segment: "Beading Wire",
    color: "Clear",
    size: "100 yards",
    material: "Nylon",
    mpn: "BW-123456",
    url: "https://www.example.com/product-page8",
    rating: { rate: 4.5, count: 60 },
    review: [
      {
        author: "Michael Brown",
        reviewBody: "Strong and flexible wire for all my jewelry projects.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Crafting Scissors",
    description: "Precision scissors for all your crafting needs.",
    image: "https://www.example.com/product-image9.jpg",
    brand: { name: "CraftyTools" },
    offers: {
      "@type": "Offer",
      price: 12.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "SCISSORS-001",
    },
    department: "Arts & Crafts",
    category: "Paper Crafts",
    subcategory: "Crafting Tools & Equipment",
    segment: "Scissors",
    color: "Red",
    size: "8 inches",
    material: "Stainless Steel",
    mpn: "CS-123456",
    url: "https://www.example.com/product-page9",
    rating: { rate: 4.8, count: 45 },
    review: [
      {
        author: "Samantha White",
        reviewBody: "These scissors cut through paper like butter!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Embossing Folder Set",
    description:
      "A set of embossing folders for adding texture to your crafts.",
    image: "https://www.example.com/product-image10.jpg",
    brand: { name: "TextureCraft" },
    offers: {
      "@type": "Offer",
      price: 19.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "EMBOSS-001",
    },
    department: "Arts & Crafts",
    category: "Paper Crafts",
    subcategory: "Embellishments & Decorations",
    segment: "Embossing Folders",
    color: "Multi",
    size: "Set of 5",
    material: "Plastic",
    mpn: "EF-123456",
    url: "https://www.example.com/product-page10",
    rating: { rate: 4.6, count: 30 },
    review: [
      {
        author: "Laura Green",
        reviewBody: "These folders create beautiful textures on paper!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Wax",
    description: "High-quality wax for a brilliant shine on your car.",
    image: "https://www.example.com/product-image1.jpg",
    brand: { name: "ShinePro" },
    offers: {
      "@type": "Offer",
      price: 14.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "WAX-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Care",
    subcategory: "Car Wash & Wax",
    segment: "Car Wax",
    color: "Yellow",
    size: "16 oz",
    material: "Wax",
    mpn: "CW-123456",
    url: "https://www.example.com/product-page1",
    rating: { rate: 4.5, count: 150 },
    review: [
      {
        author: "John Doe",
        reviewBody: "This wax gives my car a fantastic shine!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Motorcycle Helmet",
    description: "A durable and stylish helmet for motorcycle riders.",
    image: "https://www.example.com/product-image2.jpg",
    brand: { name: "RiderSafe" },
    offers: {
      "@type": "Offer",
      price: 89.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "HELMET-001",
    },
    department: "Automobile & Motorcycle",
    category: "Motorcycle Gear",
    subcategory: "Riding Gear (Helmets, Jackets, Gloves)",
    segment: "Motorcycle Helmet",
    color: "Black",
    size: "Medium",
    material: "Polycarbonate",
    mpn: "MH-123456",
    url: "https://www.example.com/product-page2",
    rating: { rate: 4.8, count: 200 },
    review: [
      {
        author: "Jane Smith",
        reviewBody: "Comfortable and safe helmet for long rides.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Floor Mats",
    description: "All-weather floor mats to protect your car's interior.",
    image: "https://www.example.com/product-image3.jpg",
    brand: { name: "AutoGuard" },
    offers: {
      "@type": "Offer",
      price: 49.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "MATS-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Parts & Accessories",
    subcategory: "Interior Accessories",
    segment: "Floor Mats",
    color: "Black",
    size: "Universal Fit",
    material: "Rubber",
    mpn: "FM-123456",
    url: "https://www.example.com/product-page3",
    rating: { rate: 4.6, count: 120 },
    review: [
      {
        author: "Mark Johnson",
        reviewBody: "These mats fit perfectly and are easy to clean.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Motorcycle Gloves",
    description: "Protective gloves for motorcycle riders.",
    image: "https://www.example.com/product-image4.jpg",
    brand: { name: "GripSafe" },
    offers: {
      "@type": "Offer",
      price: 39.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "GLOVES-001",
    },
    department: "Automobile & Motorcycle",
    category: "Motorcycle Gear",
    subcategory: "Riding Gear (Helmets, Jackets, Gloves)",
    segment: "Motorcycle Gloves",
    color: "Black",
    size: "Large",
    material: "Leather",
    mpn: "MG-123456",
    url: "https://www.example.com/product-page4",
    rating: { rate: 4.7, count: 90 },
    review: [
      {
        author: "Emily Davis",
        reviewBody: "Great grip and comfort while riding.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Battery Charger",
    description: "A reliable charger for your car battery.",
    image: "https://www.example.com/product-image5.jpg",
    brand: { name: "PowerCharge" },
    offers: {
      "@type": "Offer",
      price: 59.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "CHARGER-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Parts & Accessories",
    subcategory: "Performance Parts",
    segment: "Battery Charger",
    color: "Red",
    size: "Compact",
    material: "Plastic",
    mpn: "BC-123456",
    url: "https://www.example.com/product-page5",
    rating: { rate: 4.4, count: 80 },
    review: [
      {
        author: "Tom White",
        reviewBody: "Works perfectly for my car battery.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Motorcycle Cover",
    description: "Durable cover to protect your motorcycle from the elements.",
    image: "https://www.example.com/product-image6.jpg",
    brand: { name: "WeatherGuard" },
    offers: {
      "@type": "Offer",
      price: 29.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "COVER-001",
    },
    department: "Automobile & Motorcycle",
    category: "Motorcycle Parts & Accessories",
    subcategory: "Motorcycle Accessories",
    segment: "Motorcycle Cover",
    color: "Gray",
    size: "Universal Fit",
    material: "Polyester",
    mpn: "MC-123456",
    url: "https://www.example.com/product-page6",
    rating: { rate: 4.6, count: 70 },
    review: [
      {
        author: "Anna Brown",
        reviewBody: "Keeps my motorcycle safe from rain and dust.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Jump Starter",
    description: "Portable jump starter for emergencies.",
    image: "https://www.example.com/product-image7.jpg",
    brand: { name: "JumpStart" },
    offers: {
      "@type": "Offer",
      price: 79.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "JUMP-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Parts & Accessories",
    subcategory: "Performance Parts",
    segment: "Jump Starter",
    color: "Black",
    size: "Compact",
    material: "Plastic",
    mpn: "JS-123456",
    url: "https://www.example.com/product-page7",
    rating: { rate: 4.8, count: 100 },
    review: [
      {
        author: "Michael Green",
        reviewBody: "A lifesaver during emergencies!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Seat Covers",
    description: "Stylish and protective seat covers for your car.",
    image: "https://www.example.com/product-image8.jpg",
    brand: { name: "SeatGuard" },
    offers: {
      "@type": "Offer",
      price: 49.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "SEATCOVERS-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Parts & Accessories",
    subcategory: "Interior Accessories",
    segment: "Seat Covers",
    color: "Black",
    size: "Universal Fit",
    material: "Fabric",
    mpn: " SEAT-123456",
    url: "https://www.example.com/product-page8",
    rating: { rate: 4.5, count: 60 },
    review: [
      {
        author: "Laura Green",
        reviewBody: "These seat covers fit perfectly and look great!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Tire Pressure Gauge",
    description:
      "Accurate tire pressure gauge for maintaining optimal tire pressure.",
    image: "https://www.example.com/product-image9.jpg",
    brand: { name: "GaugePro" },
    offers: {
      "@type": "Offer",
      price: 9.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "GAUGE-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Parts & Accessories",
    subcategory: "Performance Parts",
    segment: "Tire Pressure Gauge",
    color: "Black",
    size: "Compact",
    material: "Plastic",
    mpn: "TPG-123456",
    url: "https://www.example.com/product-page9",
    rating: { rate: 4.4, count: 50 },
    review: [
      {
        author: "Tom White",
        reviewBody: "Easy to use and very accurate!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Car Emergency Kit",
    description: "Comprehensive emergency kit for roadside assistance.",
    image: "https://www.example.com/product-image10.jpg",
    brand: { name: "SafetyFirst" },
    offers: {
      "@type": "Offer",
      price: 39.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "EMERGENCY-KIT-001",
    },
    department: "Automobile & Motorcycle",
    category: "Car Parts & Accessories",
    subcategory: "Performance Parts",
    segment: "Emergency Kit",
    color: "Red",
    size: "Standard",
    material: "Various",
    mpn: "EK-123456",
    url: "https://www.example.com/product-page10",
    rating: { rate: 4.9, count: 30 },
    review: [
      {
        author: "Anna Brown",
        reviewBody: "This kit has everything you need for emergencies!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Diapers Size 1",
    description: "Soft and absorbent diapers for newborns.",
    image: "https://www.example.com/product-image1.jpg",
    brand: { name: "BabySoft" },
    offers: {
      "@type": "Offer",
      price: 24.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "DIAPER-001",
    },
    department: "Baby",
    category: "Diapers & Wipes",
    subcategory: "Diapers",
    segment: "Newborn Diapers",
    color: "White",
    size: "Size 1",
    material: "Cotton",
    mpn: "D1-123456",
    url: "https://www.example.com/product-page1",
    rating: { rate: 4.8, count: 300 },
    review: [
      {
        author: "Emily Davis",
        reviewBody: "These diapers are super soft and absorbent!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby Wipes",
    description: "Gentle and effective wipes for cleaning your baby.",
    image: "https://www.example.com/product-image2.jpg",
    brand: { name: "GentleCare" },
    offers: {
      "@type": "Offer",
      price: 19.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "WIPES-001",
    },
    department: "Baby",
    category: "Diapers & Wipes",
    subcategory: "Wipes & Cleaning Supplies",
    segment: "Baby Wipes",
    color: "White",
    size: "Pack of 100",
    material: "Cotton",
    mpn: "W-123456",
    url: "https://www.example.com/product-page2",
    rating: { rate: 4.7, count: 250 },
    review: [
      {
        author: "John Smith",
        reviewBody: "These wipes are perfect for my baby's sensitive skin.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby Bottles",
    description: "BPA-free baby bottles for safe feeding.",
    image: "https://www.example.com/product-image3.jpg",
    brand: { name: "FeedingTime" },
    offers: {
      "@type": "Offer",
      price: 29.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "BOTTLE-001",
    },
    department: "Baby",
    category: "Feeding & Nursing",
    subcategory: "Bottles & Feeding Accessories",
    segment: "Baby Bottles",
    color: "Clear",
    size: "Set of 3",
    material: "Plastic",
    mpn: "B-123456",
    url: "https://www.example.com/product-page3",
    rating: { rate: 4.6, count: 180 },
    review: [
      {
        author: "Sarah Lee",
        reviewBody: "These bottles are easy to clean and great for feeding.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Breast Pump",
    description: "Efficient breast pump for nursing mothers.",
    image: "https://www.example.com/product-image4.jpg",
    brand: { name: "MommyCare" },
    offers: {
      "@type": "Offer",
      price: 79.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "PUMP-001",
    },
    department: "Baby",
    category: "Feeding & Nursing",
    subcategory: "Breastfeeding Supplies",
    segment: "Breast Pump",
    color: "White",
    size: "Standard",
    material: "Plastic",
    mpn: "BP-123456",
    url: "https://www.example.com/product-page4",
    rating: { rate: 4.5, count: 150 },
    review: [
      {
        author: "Anna Brown",
        reviewBody: "This pump is very effective and easy to use.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby Sleep Sack",
    description: "Cozy sleep sack for a comfortable night's sleep.",
    image: "https://www.example.com/product-image5.jpg",
    brand: { name: "SnuggleBugs" },
    offers: {
      "@type": "Offer",
      price: 34.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "SLEEP-001",
    },
    department: "Baby",
    category: "Clothing & Bedding",
    subcategory: "Baby Bedding & Sleepwear",
    segment: "Sleep Sack",
    color: "Blue",
    size: "Medium",
    material: "Cotton",
    mpn: "SS-123456",
    url: "https://www.example.com/product-page5",
    rating: { rate: 4.9, count: 120 },
    review: [
      {
        author: "Michael Green",
        reviewBody: "This sleep sack keeps my baby warm and cozy!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby Monitor",
    description: "Reliable baby monitor with video and audio.",
    image: "https://www.example.com/product-image6.jpg",
    brand: { name: "SafeWatch" },
    offers: {
      "@type": "Offer",
      price: 99.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "MONITOR-001",
    },
    department: "Baby",
    category: "Feeding & Nursing",
    subcategory: "Baby Monitors",
    segment: "Video Monitor",
    color: "White",
    size: "Standard",
    material: "Plastic",
    mpn: "BM-123456",
    url: "https://www.example.com/product-page6",
    rating: { rate: 4.8, count: 200 },
    review: [
      {
        author: "Laura White",
        reviewBody: "This monitor gives me peace of mind while my baby sleeps.",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby Bath Tub",
    description: "Ergonomic baby bath tub for safe bathing.",
    image: "https://www.example.com/product-image7.jpg",
    brand: { name: "BathTime" },
    offers: {
      "@type": "Offer",
      price: 39.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "BATHTUB-001",
    },
    department: "Baby",
    category: "Toys & Games",
    subcategory: "Bath Toys",
    segment: "Bath Tub",
    color: "Blue",
    size: "Standard",
    material: "Plastic",
    mpn: "BT-123456",
    url: "https://www.example.com/product-page7",
    rating: { rate: 4.7, count: 90 },
    review: [
      {
        author: "Tom Brown",
        reviewBody: "Perfect size for my baby and easy to clean!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Plush Toy",
    description: "Soft and cuddly plush toy for babies.",
    image: "https://www.example.com/product-image8.jpg",
    brand: { name: "CuddleBuddy" },
    offers: {
      "@type": "Offer",
      price: 19.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "PLUSH-001",
    },
    department: "Baby",
    category: "Toys & Games",
    subcategory: "Plush Toys & Stuffed Animals",
    segment: "Plush Toy",
    color: "Pink",
    size: "Medium",
    material: "Cotton",
    mpn: "PT-123456",
    url: "https://www.example.com/product-page8",
    rating: { rate: 4.9, count: 150 },
    review: [
      {
        author: "Anna Green",
        reviewBody: "My baby loves this plush toy!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby Carrier",
    description: "Comfortable baby carrier for hands-free carrying.",
    image: "https://www.example.com/product-image9.jpg",
    brand: { name: "CarryMe" },
    offers: {
      "@type": "Offer",
      price: 49.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "CARRIER-001",
    },
    department: "Baby",
    category: "Clothing & Bedding",
    subcategory: "Baby Gear & Accessories",
    segment: "Baby Carrier",
    color: "Gray",
    size: "One Size",
    material: "Cotton",
    mpn: "BC-123456",
    url: "https://www.example.com/product-page9",
    rating: { rate: 4.8, count: 100 },
    review: [
      {
        author: "Michael White",
        reviewBody: "This carrier is so comfortable for both me and my baby!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
  {
    name: "Baby High Chair",
    description: "Adjustable high chair for safe feeding.",
    image: "https://www.example.com/product-image10.jpg",
    brand: { name: "FeedingTime" },
    offers: {
      price: 89.99,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      sku: "HIGHCHAIR-001",
    },
    department: "Baby",
    category: "Feeding & Nursing",
    subcategory: "Feeding Accessories",
    segment: "High Chair",
    color: "White",
    size: "Adjustable",
    material: "Plastic",
    mpn: "HC-123456",
    url: "https://www.example.com/product-page10",
    rating: { rate: 4.7, count: 80 },
    review: [
      {
        author: "Laura Brown",
        reviewBody: "This high chair is perfect for my growing baby!",
        reviewRating: {
          ratingValue: 5,
          bestRating: 5,
          worstRating: 1,
        },
      },
    ],
  },
];
  
export default products;
